# Generated by Django 3.1.1 on 2020-09-26 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('token', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=1000)),
                ('hdo', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=50)),
                ('temporary_address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('signature', models.ImageField(upload_to='user_signature')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mac_technology.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='User_CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('experience_year', models.IntegerField(null=True)),
                ('skills', models.TextField(max_length=200, null=True)),
                ('reference_name', models.CharField(max_length=100, null=True)),
                ('refrence_email', models.CharField(max_length=100, null=True)),
                ('reference_contact', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mac_technology.user_detail')),
            ],
        ),
    ]
