# Generated by Django 3.1.1 on 2020-09-28 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mac_technology', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_cv',
            old_name='refrence_email',
            new_name='reference_email',
        ),
        migrations.RemoveField(
            model_name='user_cv',
            name='experience_year',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='temporary_address',
        ),
        migrations.AddField(
            model_name='user_cv',
            name='reference_position',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_cv',
            name='reference_workat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_profile',
            name='country',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_profile',
            name='local_place',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=10)),
                ('cv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mac_technology.user_cv')),
            ],
        ),
        migrations.CreateModel(
            name='Apply_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mac_technology.user_detail')),
            ],
        ),
    ]
