# Generated by Django 3.1.1 on 2020-10-03 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mac_technology', '0002_auto_20200928_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_cv',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mac_technology.user_detail'),
        ),
    ]
