# Generated by Django 3.1.1 on 2020-10-03 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mac_technology', '0003_auto_20201002_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=100)),
                ('work_type', models.CharField(max_length=20)),
                ('payment_type', models.CharField(max_length=50)),
                ('range_of_salary', models.IntegerField(blank=True, null=True)),
                ('plus_services', models.CharField(max_length=200)),
                ('experience_year', models.IntegerField()),
                ('task_and_responsibilities', models.TextField(max_length=200)),
                ('qualification_and_experience', models.TextField(max_length=300)),
                ('expiry_date', models.DateTimeField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
