# Generated by Django 3.1.1 on 2020-10-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac_technology', '0005_auto_20201003_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cv',
            name='experience_detail',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_cv',
            name='education',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
