# Generated by Django 3.1.1 on 2020-10-05 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mac_technology', '0006_auto_20201004_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply_job',
            name='position',
        ),
        migrations.AddField(
            model_name='apply_job',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mac_technology.vacancy_detail'),
        ),
        migrations.AlterField(
            model_name='apply_job',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mac_technology.user_detail'),
        ),
    ]
