# Generated by Django 3.1.1 on 2020-10-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac_technology', '0007_auto_20201005_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('position', models.CharField(max_length=150)),
                ('Contract_detail', models.IntegerField(blank=True, default=0, null=True)),
                ('signature_value', models.CharField(max_length=550)),
                ('signature_bool', models.BooleanField(default=False)),
            ],
        ),
    ]
