# Generated by Django 3.1.1 on 2020-10-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac_technology', '0008_contract_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_detail',
            name='salary',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
