# Generated by Django 3.1.1 on 2020-10-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mac_technology', '0009_contract_detail_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract_detail',
            old_name='Contract_detail',
            new_name='contract_time',
        ),
    ]
